import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { PrintButton } from "@/components/admin/print-button";
import { requireMenu } from "@/lib/auth/session";
import { formatMoney } from "@/lib/money";
import { getProjectDetail } from "@/lib/queries/admin";
import { formatDate } from "@/lib/utils";

type Props = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const detail = await getProjectDetail(slug);
  return { title: `Proposal — ${detail?.project.name ?? "Project"}` };
}

/**
 * The document a client is sent.
 *
 * **Saved as a PDF by printing it**, rather than generated by a PDF library.
 * That is a deliberate choice, not a shortcut:
 *
 *   - It adds no dependency. A PDF library is a large one, and this page would
 *     be its only user.
 *   - The thing on screen and the thing in the file are the same thing, so it
 *     cannot drift the way a separate PDF template does — the bug where the web
 *     version is fixed and the PDF still says last month's price.
 *   - Every browser can do it, and the person doing it can see exactly what they
 *     are about to send before they send it.
 *
 * The trade is that it is two clicks rather than one. If a generated file is
 * ever wanted — attached to an email automatically, say — that is the moment to
 * add the library, and this page is what it would render.
 *
 * Everything here comes from the project. **Nothing is typed twice**, so a price
 * changed on the form is changed here, and there is no second copy to forget.
 */
export default async function DocumentPage({ params }: Props) {
  await requireMenu("projects");

  const { slug } = await params;
  const detail = await getProjectDetail(slug);
  if (!detail) notFound();

  const { project, money, requirements } = detail;
  const client = project.client;

  return (
    <div className="mx-auto w-full max-w-3xl">
      {/* Everything in here is for the person preparing it, and none of it
          prints — see `print:hidden`. */}
      <div className="print:hidden">
        <Link
          href={`/projects/${project.slug}`}
          className="inline-flex items-center gap-2 text-sm text-text-muted hover:text-text"
        >
          <ArrowLeft className="size-4" aria-hidden />
          {project.name}
        </Link>

        <div className="mt-4 flex flex-wrap items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-semibold">The document</h1>
            <p className="measure mt-2 text-sm leading-relaxed text-text-muted">
              What the client is sent. Read it once before you do — anything
              missing here is missing because it is empty on the project, and the
              place to fix it is the form rather than this page.
            </p>
          </div>

          <PrintButton />
        </div>
      </div>

      {/* ------------------------------------------------------------------ */}
      <article className="mt-8 rounded-2xl border border-border bg-surface p-8 print:mt-0 print:rounded-none print:border-0 print:p-0">
        <header className="flex flex-wrap items-start justify-between gap-6 border-b border-border pb-6">
          <div>
            <p className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-text-subtle">
              Proposal
            </p>
            <h2 className="mt-2 text-xl font-semibold">{project.name}</h2>
            {project.summary && (
              <p className="measure mt-2 text-sm leading-relaxed text-text-muted">
                {project.summary}
              </p>
            )}
          </div>

          <div className="text-right text-sm">
            <p className="font-semibold">Apka Saathi Private Limited</p>
            <p className="mt-1 text-text-muted">{formatDate(new Date())}</p>
          </div>
        </header>

        {client && (
          <section className="mt-6">
            <h3 className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-text-subtle">
              Prepared for
            </h3>
            <p className="mt-2 font-medium">{client.company_name ?? client.name}</p>
            {client.company_name && (
              <p className="text-sm text-text-muted">{client.name}</p>
            )}
          </section>
        )}

        <Block title="What you asked for" body={project.client_brief} />
        <Block title="What we will build" body={project.what_we_will_do} />

        {requirements.length > 0 && (
          <section className="mt-8">
            <h3 className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-text-subtle">
              Included
            </h3>
            <ul className="mt-3 space-y-2">
              {requirements
                .filter((item) => item.status !== "dropped")
                .map((item) => (
                  <li key={item.id} className="text-sm leading-relaxed">
                    <span className="font-medium">{item.title}</span>
                    {item.description && (
                      <span className="text-text-muted"> — {item.description}</span>
                    )}
                  </li>
                ))}
            </ul>
          </section>
        )}

        <Block title="Not included" body={project.exclusions} />

        {/* ---------------------------------------------------------------- */}
        <section className="mt-8 rounded-xl border border-border p-5 print:border-border-strong">
          <h3 className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-text-subtle">
            Cost
          </h3>

          <dl className="mt-3 space-y-2 text-sm">
            <Line label="Quoted" value={formatMoney(money.quoted, project.currency)} />
            {money.discount > 0 && (
              <Line
                label="Discount"
                value={`− ${formatMoney(money.discount, project.currency)}`}
              />
            )}
            <div className="flex items-baseline justify-between gap-4 border-t border-border pt-2">
              <dt className="font-medium">Total</dt>
              <dd className="text-lg font-semibold tabular-nums">
                {formatMoney(money.total, project.currency)}
              </dd>
            </div>

            {/*
              Only shown once something has been received.

              A proposal that says "Paid: ₹0" reads as a demand rather than a
              quote, and it is the first line the reader's eye lands on.
            */}
            {money.paid > 0 && (
              <>
                <Line label="Received" value={formatMoney(money.paid, project.currency)} />
                <Line
                  label={money.overpaid > 0 ? "In credit" : "Outstanding"}
                  value={formatMoney(
                    money.overpaid > 0 ? money.overpaid : money.outstanding,
                    project.currency,
                  )}
                />
              </>
            )}
          </dl>

          {project.estimated_weeks && (
            <p className="mt-4 text-sm">
              <span className="font-medium">How long: </span>
              about {project.estimated_weeks} week
              {project.estimated_weeks === 1 ? "" : "s"} from the day we start.
            </p>
          )}
        </section>

        <Block title="Payment terms" body={project.payment_terms} />
        <Block title="Terms" body={project.terms} />

        <footer className="mt-10 border-t border-border pt-6 text-xs leading-relaxed text-text-subtle">
          <p>
            This is a proposal, not an invoice. Once you accept it we will confirm
            in writing and set up your access, and the figures above become the
            agreed amounts.
          </p>
          <p className="mt-2">Apka Saathi Private Limited</p>
        </footer>
      </article>
    </div>
  );
}

/**
 * A titled block, or nothing.
 *
 * An empty section with a heading and no words under it reads as a mistake in
 * the document. If the project has nothing written there, the reader should not
 * be told there was supposed to be.
 */
function Block({ title, body }: { title: string; body: string | null }) {
  if (!body) return null;

  return (
    <section className="mt-8">
      <h3 className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-text-subtle">
        {title}
      </h3>
      <p className="mt-3 whitespace-pre-line text-sm leading-relaxed">{body}</p>
    </section>
  );
}

function Line({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex itemsod-baseline justify-between gap-4">
      <dt className="text-text-muted">{label}</dt>
      <dd className="tabular-nums">{value}</dd>
    </div>
  );
}
